version: '3'

volumes:
  node_0_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-0/db'
  node_0_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-0/logs'
  node_0_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-0/config'
  node_1_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-1/db'
  node_1_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-1/logs'
  node_1_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-1/config'
  node_2_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-2/db'
  node_2_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-2/logs'
  node_2_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-2/config'
  node_metachain_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-metachain/db'
  node_metachain_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-metachain/logs'
  node_metachain_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/data/MyObservingSquad/node-metachain/config'
  cache:

services:
 observer-0:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8080:8080"
     - "10000:37373"
   environment:
     - SHARD=0
   volumes:
     - node_0_db:/go/elrond-go/cmd/node/db
     - node_0_logs:/go/elrond-go/cmd/node/logs
     - node_0_config:/config
   command: --destination-shard-as-observer=${SHARD_0} --validator-key-pem-file=/config/observerKey_${SHARD_0}.pem --display-name="${DISPLAY_NAME_0}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.6

 observer-1:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8081:8080"
     - "10001:37373"
   environment:
     - SHARD=1 
   volumes:
     - node_1_db:/go/elrond-go/cmd/node/db
     - node_1_logs:/go/elrond-go/cmd/node/logs
     - node_1_config:/config
   command: --destination-shard-as-observer=${SHARD_1} --validator-key-pem-file=/config/observerKey_${SHARD_1}.pem --display-name="${DISPLAY_NAME_1}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.5
 observer-2:
   image: elrondnetwork/${NODE_TAG}
   ports:
    - "8082:8080" 
    - "10002:37373"
   environment:
     - SHARD=2
   volumes:
     - node_2_db:/go/elrond-go/cmd/node/db
     - node_2_logs:/go/elrond-go/cmd/node/logs
     - node_2_config:/config
   command: --destination-shard-as-observer=${SHARD_2} --validator-key-pem-file=/config/observerKey_${SHARD_2}.pem --display-name="${DISPLAY_NAME_2}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.4

 observer-meta:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8083:8080"
     - "10003:37373"
   environment:
     - SHARD=metachain
   volumes:
     - node_metachain_db:/go/elrond-go/cmd/node/db
     - node_metachain_logs:/go/elrond-go/cmd/node/logs
     - node_metachain_config:/config
   command: --destination-shard-as-observer=${SHARD_M} --validator-key-pem-file=/config/observerKey_${SHARD_M}.pem --display-name="${DISPLAY_NAME_M}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.3

 proxy:
   image: elrondnetwork/${PROXY_TAG}
   ports:
     - "8079:8079"
   environment:
     - IP=10.0.0.2
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.2

networks:
  elrond-squad:
    ipam:
      config:
        - subnet: 10.0.0.0/24